
categories:
  - id: system
    name: システム
  - id: manufacturing
    name: 製造（鉄鋼）
  - id: blast_furnace
    name: 高炉
  - id: eaf
    name: 電炉
  - id: rolling
    name: 圧延
  - id: quality
    name: 品質
  - id: maintenance
    name: 保全
  - id: policy
    name: 政策・規制（脱炭素）
  - id: decarbonization_ops
    name: 脱炭素オペレーション（算定・LCA）
  - id: security
    name: セキュリティ
  - id: standards
    name: 標準化・規格
  - id: market
    name: 市況（コモディティ・海運・スクラップ）
  - id: ai
    name: AI
  - id: dev
    name: 開発

sources:
  # --- システム ---
  - id: aws-blog
    name: AWS Blog
    category: system
    url: https://aws.amazon.com/blogs/aws/feed/

  - id: gcp-blog
    name: Google Cloud Blog
    category: system
    url: https://cloud.google.com/blog/rss

  # --- セキュリティ ---
  - id: cisa-all
    name: CISA Cybersecurity Advisories
    category: security
    subcategory: security_ot
    url: https://www.cisa.gov/cybersecurity-advisories/all.xml

  - id: jpcert
    name: JPCERT/CC
    category: security
    subcategory: security_ot
    url: https://www.jpcert.or.jp/rss/jpcert-all.rdf

  - id: cisa-ics-advisories
    name: CISA ICS Advisories
    category: security
    subcategory: security_ot
    url: https://www.cisa.gov/cybersecurity-advisories/ics-advisories.xml

  - id: cisa-ics-medical-advisories
    name: CISA ICS Medical Advisories
    category: security
    subcategory: security_ot
    url: https://www.cisa.gov/cybersecurity-advisories/ics-medical-advisories.xml

  - id: cisa-ics-mitigation-guides
    name: CISA ICS Recommended Practices / Mitigation Guides
    category: security
    subcategory: security_ot
    url: https://www.cisa.gov/cybersecurity-advisories/ics-recommended-practices.xml

  - id: cisa-sbom
    name: CISA SBOM Resources
    category: security
    subcategory: security_ot
    url: https://www.cisa.gov/sbom.xml

  - id: cisa-known-exploited-vulns
    name: CISA Known Exploited Vulnerabilities Catalog
    category: security
    subcategory: security_ot
    url: https://www.cisa.gov/known-exploited-vulnerabilities-catalog.xml

  # --- 標準化・規格 ---
  - id: iso-news
    name: ISO News
    category: standards
    url: https://www.iso.org/contents/news/all.rss

  - id: iec-news
    name: IEC Newsroom
    category: standards
    url: https://www.iec.ch/newsroom/rss.xml

  - id: nist-news
    name: NIST News
    category: standards
    url: https://www.nist.gov/news-events/news/rss.xml

  - id: enisa-news
    name: ENISA News
    category: standards
    url: https://www.enisa.europa.eu/news/enisa-news/RSS

  - id: jisc-news
    name: JISC News (JIS)
    category: standards
    url: https://www.jisc.go.jp/newstopics/rss.xml

  # --- 市況（コモディティ・港湾/海運・スクラップ指数） ---
  - id: oilprice-commodities
    name: OilPrice.com (Commodities)
    category: market
    url: https://oilprice.com/rss/main

  - id: hellenic-shipping
    name: Hellenic Shipping News
    category: market
    url: https://www.hellenicshippingnews.com/feed/

  - id: recycling-today-ferrous
    name: Recycling Today (Ferrous)
    category: market
    url: https://www.recyclingtoday.com/rss/topic/ferrous.aspx

  # --- AI ---
  - id: openai-news
    name: OpenAI News
    category: ai
    url: https://openai.com/news/rss.xml

  - id: google-ai-blog
    name: Google AI Blog
    category: ai
    url: https://ai.googleblog.com/feeds/posts/default

  - id: deepmind-blog
    name: Google DeepMind Blog
    category: ai
    url: https://deepmind.google/blog/rss.xml

  - id: meta-ai
    name: Meta AI Blog
    category: ai
    url: https://ai.facebook.com/blog/rss/

  - id: microsoft-ai
    name: Microsoft AI Blog
    category: ai
    url: https://blogs.microsoft.com/ai/feed/

  - id: aws-ml
    name: AWS Machine Learning Blog
    category: ai
    url: https://aws.amazon.com/blogs/machine-learning/feed/

  - id: huggingface-blog
    name: Hugging Face Blog
    category: ai
    url: https://huggingface.co/blog/feed.xml

  - id: arxiv-ai
    name: arXiv AI (cs.AI)
    category: ai
    url: http://export.arxiv.org/rss/cs.AI

  - id: arxiv-ml
    name: arXiv Machine Learning (cs.LG)
    category: ai
    url: http://export.arxiv.org/rss/cs.LG

  - id: github-ml
    name: GitHub Machine Learning
    category: ai
    url: https://github.blog/category/machine-learning/feed/

  # --- 製造（鉄鋼） ---
  # 鉄鋼団体・企業ニュース（鉄鋼主軸に寄せる）
  - id: worldsteel
    name: worldsteel (World Steel Association)
    category: manufacturing
    url: https://worldsteel.org/feed/

  - id: jfe-holdings
    name: JFE Holdings Releases
    category: manufacturing
    url: https://www.jfe-holdings.co.jp/rss/release.xml

  # 既存（製造/OT・ICSも残す）
  - id: mhi
    name: Mitsubishi Heavy Industries News
    category: manufacturing
    url: https://www.mhi.com/rss/mhi_news.xml

  - id: siemens-cert
    name: Siemens ProductCERT Advisories
    category: manufacturing
    url: https://www.siemens.com/cert/rss/advisories.xml

  # MES / SCADA / IIoT 専門媒体・主要ベンダ技術アラート
  # kind は tech のまま、category は manufacturing に統一し
  # 運用上は name の接頭辞でサブカテゴリを識別する
  - id: automation-world-mes
    name: "[MES] Automation World"
    category: manufacturing
    kind: tech
    region: global
    url: https://www.automationworld.com/rss.xml

  - id: control-global-scada
    name: "[SCADA] Control Global"
    category: manufacturing
    kind: tech
    region: global
    url: https://www.controlglobal.com/rss.xml

  - id: iiot-world
    name: "[IIoT] IIoT World"
    category: manufacturing
    kind: tech
    region: global
    url: https://www.iiot-world.com/feed/

  - id: inductive-automation-blog
    name: "[SCADA Vendor] Inductive Automation Blog"
    category: manufacturing
    kind: tech
    region: global
    url: https://inductiveautomation.com/blog/rss.xml

  - id: aveva-insight
    name: "[SCADA Vendor] AVEVA Insights"
    category: manufacturing
    kind: tech
    region: global
    url: https://www.aveva.com/en/perspectives/blog/rss/

  - id: rockwell-blog
    name: "[MES Vendor] Rockwell Automation Blog"
    category: manufacturing
    kind: tech
    region: global
    url: https://www.rockwellautomation.com/en-us/company/news/blogs.feed.xml

  - id: siemens-industry-blog
    name: "[MES/SCADA Vendor] Siemens Industry Blog"
    category: manufacturing
    kind: tech
    region: global
    url: https://blogs.sw.siemens.com/feed/

  # --- 高炉 ---
  - id: worldsteel-ironmaking
    name: worldsteel (Ironmaking related)
    category: blast_furnace
    url: https://worldsteel.org/feed/

  - id: primetals-ironmaking
    name: Primetals Technologies News (Ironmaking)
    category: blast_furnace
    url: https://www.primetals.com/news-media/news/rss/

  # --- 電炉 ---
  - id: steel-times-eaf
    name: Steel Times International (EAF)
    category: eaf
    url: https://www.steeltimesint.com/feed/

  - id: tenova-eaf
    name: Tenova News (EAF)
    category: eaf
    url: https://www.tenova.com/news/feed/

  # --- 圧延 ---
  - id: sms-rolling
    name: SMS group Newsroom (Rolling)
    category: rolling
    url: https://www.sms-group.com/company/newsroom/rss.xml

  - id: danieli-rolling
    name: Danieli News (Rolling)
    category: rolling
    url: https://www.danieli.com/en/news/rss.xml

  # --- 品質 ---
  - id: iso-quality
    name: ISO News (Quality standards)
    category: quality
    url: https://www.iso.org/contents/news/all.rss

  - id: zeiss-quality
    name: ZEISS Metrology Newsroom
    category: quality
    url: https://www.zeiss.com/metrology/en/news-events/newsroom/rss.xml

  # --- 保全 ---
  - id: skf-maintenance
    name: SKF Blog (Reliability/Maintenance)
    category: maintenance
    url: https://blog.skf.com/feed/

  - id: fiix-maintenance
    name: Fiix CMMS Blog (Maintenance)
    category: maintenance
    url: https://fiixsoftware.com/blog/feed/

  # --- 政策・規制（脱炭素） ---
  - id: eu-clima
    name: European Commission - DG CLIMA
    category: policy
    url: https://ec.europa.eu/newsroom/clima/feed?item_type_id=1536&lang=en&orderby=item_date

  - id: meti-en
    name: METI (Japan) - English RSS
    category: policy
    url: https://www.meti.go.jp/ml_index_en_atom.xml

  - id: eu-cbam
    name: European Commission - CBAM (Taxation and Customs Union)
    category: policy
    url: https://ec.europa.eu/newsroom/taxation_customs/feed?item_type_id=1536&lang=en&orderby=item_date

  # --- 脱炭素オペレーション（算定・LCA） ---
  - id: ghg-protocol
    name: GHG Protocol Updates
    category: decarbonization_ops
    url: https://ghgprotocol.org/blog/feed

  - id: env-japan
    name: Ministry of the Environment, Japan - Press Releases
    category: decarbonization_ops
    url: https://www.env.go.jp/press/rss.xml

  - id: iso-lca
    name: ISO News (LCA/Standards primary source)
    category: decarbonization_ops
    url: https://www.iso.org/contents/news/all.rss

  # --- 開発 ---
  - id: github-blog
    name: GitHub Blog
    category: dev
    url: https://github.blog/feed/

  - id: microsoft-devblogs
    name: Microsoft DevBlogs
    category: dev
    url: https://devblogs.microsoft.com/feed/

  - id: madonomori
    name: 窓の杜 (Impress Watch)
    category: dev   # systemでもOK（好みで）
    url: https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf



      # --- ニュース（全国 / 世界） ---

  - name: ITmedia NEWS
    kind: news
    region: jp
    rss:
      - https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml

  
  - name: Impress Watch (INTERNET Watch)
    kind: news
    region: jp
    rss:
      - https://www.watch.impress.co.jp/data/rss/1.0/ipw/feed.rdf

  - name: INTERNET Watch
    kind: news
    region: jp
    rss:
      - https://internet.watch.impress.co.jp/data/rss/1.0/iw/feed.rdf

  - name: Forest Watch
    kind: news
    region: jp
    rss:
      - https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf

  - id: jiji-top
    name: Jiji Press (Japan)
    category: news
    kind: news
    region: jp
    url: https://www.jiji.com/rss/ranking.rdf

  - id: bbc-world
    name: BBC World (Global)
    category: news
    kind: news
    region: global
    url: https://feeds.bbci.co.uk/news/world/rss.xml
