
categories:
  - id: system
    name: システム
  - id: manufacturing
    name: 製造（鉄鋼）
  - id: blast_furnace
    name: 高炉
  - id: eaf
    name: 電炉
  - id: rolling
    name: 圧延
  - id: quality
    name: 品質
  - id: maintenance
    name: 保全
  - id: environment
    name: 環境（CO2・規制）
  - id: security
    name: セキュリティ
  - id: ai
    name: AI
  - id: dev
    name: 開発

sources:
  # --- システム ---
  - id: aws-blog
    name: AWS Blog
    category: system
    url: https://aws.amazon.com/blogs/aws/feed/

  - id: gcp-blog
    name: Google Cloud Blog
    category: system
    url: https://cloud.google.com/blog/rss

  # --- セキュリティ ---
  - id: cisa-all
    name: CISA Cybersecurity Advisories
    category: security
    url: https://www.cisa.gov/cybersecurity-advisories/all.xml

  - id: jpcert
    name: JPCERT/CC
    category: security
    url: https://www.jpcert.or.jp/rss/jpcert-all.rdf

  # --- AI ---
  - id: openai-news
    name: OpenAI News
    category: ai
    url: https://openai.com/news/rss.xml

  - id: google-ai-blog
    name: Google AI Blog
    category: ai
    url: https://ai.googleblog.com/feeds/posts/default

  - id: deepmind-blog
    name: Google DeepMind Blog
    category: ai
    url: https://deepmind.google/blog/rss.xml

  - id: meta-ai
    name: Meta AI Blog
    category: ai
    url: https://ai.facebook.com/blog/rss/

  - id: microsoft-ai
    name: Microsoft AI Blog
    category: ai
    url: https://blogs.microsoft.com/ai/feed/

  - id: aws-ml
    name: AWS Machine Learning Blog
    category: ai
    url: https://aws.amazon.com/blogs/machine-learning/feed/

  - id: huggingface-blog
    name: Hugging Face Blog
    category: ai
    url: https://huggingface.co/blog/feed.xml

  - id: arxiv-ai
    name: arXiv AI (cs.AI)
    category: ai
    url: http://export.arxiv.org/rss/cs.AI

  - id: arxiv-ml
    name: arXiv Machine Learning (cs.LG)
    category: ai
    url: http://export.arxiv.org/rss/cs.LG

  - id: github-ml
    name: GitHub Machine Learning
    category: ai
    url: https://github.blog/category/machine-learning/feed/

  # --- 製造（鉄鋼） ---
  # 鉄鋼団体・企業ニュース（鉄鋼主軸に寄せる）
  - id: worldsteel
    name: worldsteel (World Steel Association)
    category: manufacturing
    url: https://worldsteel.org/feed/

  - id: jfe-holdings
    name: JFE Holdings Releases
    category: manufacturing
    url: https://www.jfe-holdings.co.jp/rss/release.xml

  # 既存（製造/OT・ICSも残す）
  - id: mhi
    name: Mitsubishi Heavy Industries News
    category: manufacturing
    url: https://www.mhi.com/rss/mhi_news.xml

  - id: siemens-cert
    name: Siemens ProductCERT Advisories
    category: manufacturing
    url: https://www.siemens.com/cert/rss/advisories.xml

  # --- 高炉 ---
  - id: worldsteel-ironmaking
    name: worldsteel (Ironmaking related)
    category: blast_furnace
    url: https://worldsteel.org/feed/

  - id: primetals-ironmaking
    name: Primetals Technologies News (Ironmaking)
    category: blast_furnace
    url: https://www.primetals.com/news-media/news/rss/

  # --- 電炉 ---
  - id: steel-times-eaf
    name: Steel Times International (EAF)
    category: eaf
    url: https://www.steeltimesint.com/feed/

  - id: tenova-eaf
    name: Tenova News (EAF)
    category: eaf
    url: https://www.tenova.com/news/feed/

  # --- 圧延 ---
  - id: sms-rolling
    name: SMS group Newsroom (Rolling)
    category: rolling
    url: https://www.sms-group.com/company/newsroom/rss.xml

  - id: danieli-rolling
    name: Danieli News (Rolling)
    category: rolling
    url: https://www.danieli.com/en/news/rss.xml

  # --- 品質 ---
  - id: iso-quality
    name: ISO News (Quality standards)
    category: quality
    url: https://www.iso.org/contents/news/all.rss

  - id: zeiss-quality
    name: ZEISS Metrology Newsroom
    category: quality
    url: https://www.zeiss.com/metrology/en/news-events/newsroom/rss.xml

  # --- 保全 ---
  - id: skf-maintenance
    name: SKF Blog (Reliability/Maintenance)
    category: maintenance
    url: https://blog.skf.com/feed/

  - id: fiix-maintenance
    name: Fiix CMMS Blog (Maintenance)
    category: maintenance
    url: https://fiixsoftware.com/blog/feed/

  # --- 環境（CO2・規制） ---
  - id: eu-clima
    name: European Commission - DG CLIMA
    category: environment
    url: https://ec.europa.eu/newsroom/clima/feed?item_type_id=1536&lang=en&orderby=item_date

  - id: meti-en
    name: METI (Japan) - English RSS
    category: environment
    url: https://www.meti.go.jp/ml_index_en_atom.xml

  # --- 開発 ---
  - id: github-blog
    name: GitHub Blog
    category: dev
    url: https://github.blog/feed/

  - id: microsoft-devblogs
    name: Microsoft DevBlogs
    category: dev
    url: https://devblogs.microsoft.com/feed/

  - id: madonomori
    name: 窓の杜 (Impress Watch)
    category: dev   # systemでもOK（好みで）
    url: https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf



      # --- ニュース（全国 / 世界） ---

  - name: ITmedia NEWS
    kind: news
    region: jp
    rss:
      - https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml

  
  - name: Impress Watch (INTERNET Watch)
    kind: news
    region: jp
    rss:
      - https://www.watch.impress.co.jp/data/rss/1.0/ipw/feed.rdf

  - name: INTERNET Watch
    kind: news
    region: jp
    rss:
      - https://internet.watch.impress.co.jp/data/rss/1.0/iw/feed.rdf

  - name: Forest Watch
    kind: news
    region: jp
    rss:
      - https://forest.watch.impress.co.jp/data/rss/1.0/wf/feed.rdf

  - id: jiji-top
    name: Jiji Press (Japan)
    category: news
    kind: news
    region: jp
    url: https://www.jiji.com/rss/ranking.rdf

  - id: bbc-world
    name: BBC World (Global)
    category: news
    kind: news
    region: global
    url: https://feeds.bbci.co.uk/news/world/rss.xml
